Repository babeuloula/github-pr-review, pull requests merged in 2019-10, with the labels that each got.

#34 added repositoryVulnerabilityAlert to notifications
  src/Enum/NotificationType.php
Labels: bug, hacktoberfest

#37 Fix Other Repos reasons notifs
  src/Service/Github/NotificationService.php
Labels: bug

#38 Add undefined notification type to project's Enum
  src/Enum/NotificationType.php
Labels: bug, hacktoberfest

#40 Filter on a specific repository
  README.md
  src/Service/Github/PullRequestFilterService.php
Labels: enhancement

#41 Fix multiple repo: filter on request
  src/Service/Github/PullRequestFilterService.php
Labels: bug

#42 Prevent dropdown to open if empty on refresh
  templates/github/pull-request/filtersNotifications.html.twig
  templates/github/pull-request/filtersPullRequests.html.twig
Labels: enhancement, hacktoberfest

#43 Remember closed collapses
  templates/github/pull-request/filters.html.twig
  templates/github/pull-request/filtersNotifications.html.twig
  templates/github/pull-request/filtersPullRequests.html.twig
Labels: enhancement

#47 Fix issue #45
  README.md
Labels: bug

#49 Update reload system
  public/css/pull-request.css
  public/js/modals.js
  public/js/pull-request.js
  templates/base.html.twig
  templates/github/pull-request/filters.html.twig
  templates/github/pull-request/filtersNotifications.html.twig
  templates/github/pull-request/filtersPullRequests.html.twig
  templates/github/pull-request/labels.html.twig
Labels: enhancement

#52 Change 'Next reload at:' by 'Next reload in:'
  public/js/pull-request.js
  templates/github/pull-request/filters.html.twig
Labels: enhancement

#54 Update babeuloula/phpcs to v1.0.1
  composer.lock
  src/Controller/MarkAsReadNotificationController.php
  src/Controller/ReloadNotificationController.php
  src/Controller/ReloadPullRequestController.php
Labels: update composer
